### ISSUE TITLE
مشکل در هاور روی روز های ماه

### ISSUE THREAD

**Issue by masoudtajer** [ariaieboy/filament-jalali#2]
سلام
زمانی که روی روز های ماه هاور میشه میپره ماه بعدی

https://github.com/user-attachments/assets/6ff26942-8380-4276-b967-c28db8b743c8

**Comment by ariaieboy** [comment]
@masoudtajer ویدئویی که میخواستید آپلود کنید درست آپلود نشده است.

**Comment by masoudtajer** [comment]
مجدد آپلود شد

**Comment by ariaieboy** [comment]
@masoudtajer 
لطفا کدی که استفاده میکنید برای نمایش تقویم ارسال کنید.
و اگر از ariaieboy/filament-jalali-datetimepicker استفاده میکنید آپگرید کنید به ariaieboy/filament-jalali و مجدد بررسی کنید ببینید مشکل هنوز وجود داره یا خیر

**Comment by masoudtajer** [comment]
بله از پکیج جدید استفاده میکنم.
![1](https://github.com/user-attachments/assets/0f878c98-81de-4646-8bd3-78c580d2660a)

این هم کد:
```
public static function form(Form $form): Form
    {
        return $form
            ->schema([
                TextareaLtr::make('orders')
                    ->rows(5)
                    ->label('سفارشات')
                    ->string(),
                DateTimePicker::make('send_at')
                    ->jalali()
                    ->label('تاریخ ارسال')
                    ->format('Y-m-d H:i')
                    ->seconds(false)
                    ->displayFormat('Y/m/d H:i')
                    ->minDate(now()->toDateString())
            ])
            ->columns(1);
    }
    ```

**Comment by ariaieboy** [comment]
لطفا ورژن 1.0.1 را بررسی کنید در صورتیکه مشکل همچنان پابرجا بود یک ریپوزیتوری پابلیک ایجاد کنید که با حداقل کد مورد نیاز این مشکل را نشان بده و لینک ریپو را ارسال کنید تا مجدد بررسی کنم.

**Comment by masoudtajer** [comment]
سلام همچنان مشکل وجود داره؟
ریپوی پابلیک منظورتون یه پروژه لاراولی با فیلامنت و این پکیج بیارم؟

**Comment by ariaieboy** [comment]
> سلام همچنان مشکل وجود داره؟ ریپوی پابلیک منظورتون یه پروژه لاراولی با فیلامنت و این پکیج بیارم؟

بله چون من نتونستم دیگه این مشکل با ورژن جدید ایجاد کنم

**Comment by masoudtajer** [comment]
سلام
من یه ریپوی پابلیک ساختم و همچنان این مشکل وجود داره.
این لینک ریپو:
https://github.com/masoudtajer/test-app


این هم ویدیو مشکل:


https://github.com/user-attachments/assets/625d4294-144f-450f-bbab-3d87e4f8f51b

**Comment by ariaieboy** [comment]
@masoudtajer 
زحمتتان مرورگری که استفاده میکنید با ورژنش و سیستم عاملتونم بگید که من بتونم دقیق تر بررسی کنم

**Comment by masoudtajer** [comment]
بله خیلی ممنون
ویندوز:
Windows 11 Pro
23H2

مرورگر:
chrome
Version 130.0.6723.70 (Official Build) (64-bit)

**Comment by ariaieboy** [comment]
@masoudtajer 
طبق بررسی که من کردم فقط موقعی که ماوس از روی تاریخ 11 آبان 1403 میره تاریخ به هم میریزه و میوفته روی آذر بقیه تاریخ ها را من چک کردم مشکلی نداشت. 
لطفقا شما هم بررسی کنید ببینید دقیقا همین شکل فقط موقعی که روی تاریخ 11 ابان 1403 میرید بهم میریزه تا من بتونم دقیق تر بررسی کنم.

**Comment by ariaieboy** [comment]
@masoudtajer 
ورژن 1.0.2 را تست کنید باید مشکل برطرف شده باشه.

**Comment by masoudtajer** [comment]
خیلی ممنون مشکل حل شد و اون اتفاق دوباره نیوفتاد
میتونم بپرسم دلیلش چی بود؟

**Comment by ariaieboy** [comment]
@masoudtajer 
حقیقت امر من خودمم دقیق نفهمیدم مشکل چی بود. 
چون اونطوری که من تست کردم فقط روی تاریخ 11 آبان مشکل داشت. 
فکر کردم مشکل از پلاگینی هست که تبدیل میلادی به شمسی را انجام میده و الگوریتمش مشکل داره که تست هایی که گرفتم فهمیدم نه مشکلی نداره. 
تنها چیزی که به ذهنم اومد و فکر میکنم مشکل از اونجا باشه این هست که [اینجا ](https://github.com/ariaieboy/filament-jalali/pull/5/files#diff-63abc460bff7f34aa6a6dc6f0da399c3413c47d6762b5d2da2f32c2046257784L477) ما با api خود dayjs داریم تاریخ را بر اساس هاور بروزرسانی میکنیم. پلاگین شمسی که استفاده کردیم وقتی تقویم میذاری روی `persian` قاعدتا باید روز شمسی در نظر بگیره و آپدیت کنه. که روی تمام تاریخ ها اوکی بود ولی روی 11 آبان اشتباه نکنم میومد تاریخ میلادی را آپدیت میکرد به جای شمسی و میوفتاد روی ماه آذر و خب چون یک ادج کیس بود که من روی هیچ تاریخ دیگه ای نتونستم تکرارش کنم. 
با تغییری که دادم مشکلش برطرف شد.

**Comment by masoudtajer** [comment]
باشه حتما ممنون
