### ISSUE TITLE
عدم پشتیبانی از لاراول نسخه ی 10

### ISSUE THREAD

**Issue by msalehipro** [ariaieboy/filament-jalali#3]
سلام
من یک پروژه دارم که با نسخه ی 10 لاراول هست و خواستم پکیج رو نصب کنم ولی ظاهرا با نسخه ی 10 سازگاری نداره و این خطا رو داد :

```
 Problem 1
    - Root composer.json requires ariaieboy/filament-jalali * -> satisfiable by ariaieboy/filament-jalali[1.0.0].
    - ariaieboy/filament-jalali 1.0.0 requires illuminate/contracts ^11 -> found illuminate/contracts[v11.0.0, ..., v11.29.0] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require ariaieboy/filament-jalali:*" to figure out if any version is installable, or "composer require ariaieboy/filament-jalali:^2.1" if you know which you need.
```

**Comment by ariaieboy** [comment]
@msalehipro 
سلام خدمت شما کلا هم این پروژه و هم پروژه قبلی که ادغام شد با این پروژه از لاراول ورژن ۱۰ پشتیبانی نمیکنه. 
بررسی میکنم اگر مشکل خاصی با لاراول ۱۰ وجود نداشته باشه اضافه میکنم.

**Comment by ariaieboy** [comment]
در ورژن 1.0.1 اضافه شد پشتیبانی از لاراول 10 لطفا تست کنید و اگر مشکلی وجود داشت از طریق ایجاد ایشو جدید اعلام کنید
