### ISSUE TITLE
مشکل در هاور روی روز های ماه

### ISSUE THREAD

**Issue by masoudtajer** [ariaieboy/filament-jalali#6]
سلام این مشکل همچنان وجود داره
روز های بهمن مخصوصا
مثلا 13 بهمن یا 17 بهمن
همینطور یک پروژه با این پکیج روی هاست قرار گرفته و روی مرورگر کاربر هم این مورد وجود داشته مثلا روز های آبان
ولی روی سیستم خودم روز های آبان مشکل نداره و روز های بهمن به مشکل میخوره

**Comment by ariaieboy** [comment]
@masoudtajer 
من هم روی لوکال تست کردم هم روی یکی از وبسایت هایی که روی پروداکشن هست. هیچکدوم نه توی آبان نه بهمن مشکلی نداشت. 
لطفا بررسی کنید اگر مشکل وجود داشت مجدد یک ریپو پابلیک ایجاد کنید که این مشکل را نشان بده تا بررسی کنم. 

احتمالا پلاگین را مخصوصا برای بحث تقویم کامل بازنویسی کنم. ولی منتظر انتشار فیلامنت ۴ هستم که همراه با آپدیت برای فیلامنت ۴ باشه.

**Comment by masoudtajer** [comment]
سلام 
من مجدد تست کردم و مشکلی نداشت
خیلی عجیبه اون سری به مشکل خورده بود ولی الان مشکلی نداره هیچ آپدیتی هم انجام نشده
