### ISSUE TITLE
Multiple definitions exist for class 'DatePicker' 

### ISSUE THREAD

**Issue by habibi-dev** [ariaieboy/filament-jalali#7]
Hi, after adding the `filament-jalali` project, the IDE shows this message:  
**"Multiple definitions exist for class 'DatePicker'"**  
It also encounters similar errors in other places, like:  
**"Multiple definitions exist for class 'TextColumn'"**

**Comment by ariaieboy** [comment]
از اونجایی که فیلامنت trait ماکرو اختصاصی خودش را داره IDE ها و همینطور static analyzer ها نمیتونن تشخیص بدن ماکرو هایی که ما به صورت کاستوم اضافه کردیم. به همین خاطر ما یکسری فایل برای راهنمایی به IDE ها ایجاد کردیم. که اون باعث این قضیه میشه. 
یا باید این خطا را داشته باشیم یا اتو کامپلیت برای ماکرو های کاستوم خودمون نداشته باشیم که ترجیح بنده این هست که اتو کامپلیت برام کار کنه. 

اگر روش بهتری برای شناسوندن ماکرو ها به IDE ها داشتید که این خطا را ایجاد نکنه میتونید PR بدید تا بررسی بشه.
